### ISSUE TITLE
import function

### ISSUE THREAD

**Issue by michaelvoronov** [CraneStation/wasi-sdk#14]
Hi, guys!

I am trying to declare and use import function in C code like this one (as wasi syscalls being imported):

```C
#define __IMPORT(name) \
    __attribute__((__import_module__("logger"), __import_name__(#name)))

void __wasm_log(
        const char *ptr,
        int length
) __IMPORT(wasm_log);
```

More precisely i wanted `__wasm_log` to presence in compiled wasm code in import section without body (then it would be linked with external linker). But i am getting the following result:

```bash
user:$ clang -fdeclspec --sysroot=/tmp/wasi-sdk/ --target=wasm32-unknown-wasi -o hello_world.wasm -nostartfiles -fvisibility=hidden -Wl,--no-entry,--demangle,--export=allocate,--export=deallocate,--export=invoke -- main.c
wasm-ld: error: /var/folders/main-36d4c2.o: undefined symbol: __wasm_log
clang-8: error: lld command failed with exit code 1 (use -v to see invocation)
```

What am i doing wrong?

**Comment by pchickey** [comment]
The linker needs to know that symbols are allowed to be undefined (imported) in the binary. Passing `-Wl,--allow-undefined` to clang will fix this issue. You can also put a list of import symbols in a file and use `-Wl,--allow-undefined-file=<path>`. `/opt/wasi-sdk/bin/wasm-ld --help` will show you all of the available linker options.

**Comment by michaelvoronov** [comment]
It works, thank you!

**Comment by mrpre** [comment]
@michaelvoronov Hey dude, what's your wasm runtime you are using now? Is there a runtime that support importing both custom function and wasi function ?

**Comment by michaelvoronov** [comment]
Hi, we are using [Asmble](https://github.com/cretz/asmble), it allows to write your own modules on Kotlin or any JVM like language (you can check our logger module [here](https://github.com/fluencelabs/asmble/blob/master/compiler/src/main/kotlin/asmble/run/jvm/LoggerModule.kt)). But it doesn't support WASI, and since we are concentrating on deterministic execution, we simple prohibit all imports instead our own.

P.S. Sorry for offtop:).

**Comment by LinusU** [comment]
From the WASM LLD help page it seems to me like the `import_module`/`import_name` could be used _instead_ of `--allow-undefined`. But that doesn't seem to be the case, am I missing something?

(emphasis mine)

> By default no undefined symbols are allowed in the final binary. The flag --allow-undefined results in a WebAssembly import being defined for each undefined symbol. It is then up to the runtime to provide such symbols.
> 
> **Alternatively** symbols can be marked in the source code as with the import_name and/or import_module clang attributes which signals that they are expected to be undefined at static link time.

ref: https://lld.llvm.org/WebAssembly.html

ping @pchickey

**Comment by pchickey** [comment]
Thanks @LinusU I had not seen those docs. It looks like either the docs are in error or the behavior of lld is incorrect here. @sbc100 any ideas?

**Comment by sbc100** [comment]
Yeah, if you use the `import_name` attribute you for all your symbols you don't need to pass `--allow-undefined`.

Howeve,r this features landed in https://reviews.llvm.org/D74110, which is at llvm revision 06f1a5c9c283838b8ed1d16961e41462371cd61f, which landed just 8 weeks ago so is not part of llvm 10.   You'll need to upgrade to llvm 11 pre-release to get this feature.

**Comment by LinusU** [comment]
Thanks, I'll try and remind myself to remove `--allow-undefined` when I upgrade to the next version version of WASI SDK that is based on LLVM 11 ☺️ 

Thank you all for your hard work on WASI SDK, it's seriously amazing!! ❤️ 

I'm currently using it to build popular image decoding libraries for Node.js, and it's been working great! (https://github.com/LinusU?tab=repositories&q=cwasm&type=source)
