### ISSUE TITLE
Provide newer GNU Config for packages built with autoconf

### ISSUE THREAD

**Issue by Ericson2314** [CraneStation/wasi-sdk#16]
Autoconf-based packages will need an updated GNU Config to be built. I submitted a patch to GNU config, accepted in http://git.savannah.gnu.org/cgit/config.git/commit/?id=a8d79c3130da83c7cacd6fee31b9acc53799c406, while working on https://github.com/NixOS/nixpkgs/pull/56555. Perhaps the SDK should incorperate this somehow?

**Comment by sunfishcode** [comment]
I submitted #24 to implement this.
