### ISSUE TITLE
C++ building eror: missing the LIBC++ ABI symbols

### ISSUE THREAD

**Issue by xwang98** [CraneStation/wasi-sdk#52]
Hi, we met some errors while buiding a C++ library source code. It looks the libc++ abi library is not compiled by the SDK. Can anyone kindly give some information here?

shaka@shaka-VirtualBox:~/work/test/c/eigen_test$ /opt/wasi-sdk/bin/clang++ -DEIGEN_HAS_CXX11_ATOMIC=0 -I ~/work/eigen -o test.wasm main.cpp
wasm-ld: error: /tmp/main-b1f1cc.o: undefined symbol: __cxa_begin_catch
wasm-ld: error: /tmp/main-b1f1cc.o: undefined symbol: __cxa_allocate_exception
wasm-ld: error: /tmp/main-b1f1cc.o: undefined symbol: __cxa_throw
clang-8: error: lld command failed with exit code 1 (use -v to see invocation)

**Comment by sunfishcode** [comment]
Currently, wasi-sdk requires C++ code be compiled with -fno-exceptions. libc++abi is compiled, however is is currently compiled with exception-handling support disabled.

**Comment by sunfishcode** [comment]
I've now submitted https://github.com/CraneStation/wasi-sdk/pull/53 to document the lack of exception handling support, in addition to other limitations.

**Comment by xwang98** [comment]
It is clear. Thanks! @sunfishcode
