### ISSUE TITLE
Document on how to use the SDK

### ISSUE THREAD

**Issue by anhcao142** [CraneStation/wasi-sdk#54]
Would you provide some simple examples (e.g. hello world) or some basic commands to know how to use the SDK?

**Comment by sunfishcode** [comment]
There's a link to download the SDK packages [in the README](https://github.com/CraneStation/wasi-sdk). 

For some examples of how to use it, check out this tutorial in the Wasmtime repo:

https://github.com/CraneStation/wasmtime/blob/master/docs/WASI-tutorial.md

**Comment by sunfishcode** [comment]
This seems answered; please reopen or file new issues if you have further questions!
