### ISSUE TITLE
C++ support in WASI?

### ISSUE THREAD

**Issue by DragonOsman** [CraneStation/wasi-sdk#55]
I saw C++ ABIs and stuff mentioned in the Makefile.  Does that mean it's safe to assume that WASI fully supports C++ now?  Or are there still problems?  Thanks in advance for any answers.

**Comment by sunfishcode** [comment]
C++ is supported, with the only caveat being that it doesn't support C++ exception handling yet, so you have to compile with -fno-exceptions.

**Comment by DragonOsman** [comment]
WASI sysroot doesn't support it yet, though, right?  And I guess there's no ETA on it yet either?

**Comment by sunfishcode** [comment]
It already does. If there are any problems, please file issues :-).

**Comment by DragonOsman** [comment]
Okay, cool, thanks.
