### ISSUE TITLE
LLVM trunk renamed install-clang-headers to install-clang-resource-headers

### ISSUE THREAD

**Issue by sunfishcode** [CraneStation/wasi-sdk#6]
LLVM r355340 (on March 4th) renamed install-clang-headers to install-clang-resource-headers, so we'll need to update the Makefile accordingly when using trunk and newer versions.

The LLVM revision:
> r355340 | smeenai | 2019-03-04 13:19:53 -0800 (Mon, 04 Mar 2019) | 23 lines
> 
> [build] Rename clang-headers to clang-resource-headers
Summary:
The current install-clang-headers target installs clang's resource
directory headers. This is different from the install-llvm-headers
target, which installs LLVM's API headers. We want to introduce the
corresponding target to clang, and the natural name for that new target
would be install-clang-headers. Rename the existing target to
install-clang-resource-headers to free up the install-clang-headers name
for the new target, following the discussion on cfe-dev [1].
>
> I didn't find any bots on zorg referencing install-clang-headers. I'll
send out another PSA to cfe-dev to accompany this rename.
>
> [1] http://lists.llvm.org/pipermail/cfe-dev/2019-February/061365.html
>
> Reviewers: beanz, phosek, tstellar, rnk, dim, serge-sans-paille
>
> Subscribers: mgorny, javed.absar, jdoerfert, #sanitizers, openmp-commits, lldb-commits, cfe-commits, llvm-commits
>
> Tags: #clang, #sanitizers, #lldb, #openmp, #llvm
>
> Differential Revision: https://reviews.llvm.org/D58791

**Comment by sunfishcode** [comment]
The symptom of this is that "stddef.h" is not found while building wasi-sdk.

**Comment by NineKa** [comment]
hi, after a quick fix in the makefile script (by renaming install-clang-headers to install-clang-resource-headers) it can correctly compile the wasi sysroot using trunk version. However, it seems that the expected predefined-macros test has failed. 
```
@@ -3031,20 +3031,6 @@
 #define __DEFINED_wint_t
 #define __FINITE_MATH_ONLY__ 0
 #define __FLT(x) (__IS_REAL(x) && sizeof(x) == sizeof(float))
-#define __FLT16_DECIMAL_DIG__ 5
-#define __FLT16_DENORM_MIN__ 5.9604644775390625e-8F16
-#define __FLT16_DIG__ 3
-#define __FLT16_EPSILON__ 9.765625e-4F16
-#define __FLT16_HAS_DENORM__ 1
-#define __FLT16_HAS_INFINITY__ 1
-#define __FLT16_HAS_QUIET_NAN__ 1
-#define __FLT16_MANT_DIG__ 11
-#define __FLT16_MAX_10_EXP__ 4
-#define __FLT16_MAX_EXP__ 15
-#define __FLT16_MAX__ 6.5504e+4F16
-#define __FLT16_MIN_10_EXP__ (-13)
-#define __FLT16_MIN_EXP__ (-14)
-#define __FLT16_MIN__ 6.103515625e-5F16
 #define __FLTCX(x) (__IS_CX(x) && sizeof(x) == sizeof(float complex))
 #define __FLT_DECIMAL_DIG__ 9
 #define __FLT_DENORM_MIN__ 1.40129846e-45F
Makefile:453: recipe for target 'check' failed
```

**Comment by sunfishcode** [comment]
Ah, this is some harmless differences in predefined macros between different versions of clang. I created https://github.com/CraneStation/wasi-sysroot/pull/8 to fix this.

**Comment by sunfishcode** [comment]
The install-clang-headers/install-clang-resource-headers issue is fixed in https://github.com/CraneStation/wasi-sdk/commit/8eff94c85cdc17ca00ac1b130ee8b80bb44fb00f. So once https://github.com/CraneStation/wasi-sdk/pull/13 lands, this should be fixed!

**Comment by sunfishcode** [comment]
#13 landed, so this is fixed now.
