### ISSUE TITLE
Publish sysroot as a separate downloadable

### ISSUE THREAD

**Issue by sbc100** [CraneStation/wasi-sdk#69]
We currently publish 3 version of the SDK for mac, linux and windows.  Each one contains platform specific compiler and (hopefully) identical sysroot.

This leads me to think, should we verify the sysroot are identical?   Is there any point in building the sysroot on all three platforms?

But also, many developers already have a recent version of clang on their system.  Could we, in addition, publish a sysroot-only archive, so such used can just download the sysroot and use clang from their `$PATH`?

The current setup would make way more sense if we maintained patches to upstream llvm, but we explicitly don't so we are shipping and compiler many people already have N copies of.

**Comment by jedisct1** [comment]
Can that archive be added to the wasi-sdk 8 release files?

**Comment by sbc100** [comment]
This change sadly landed after wasi-sdk-8 .. so technically it wouldn't be completely accurate to publish is as part of v8, it was the next change so yeah I think we can do it.

**Comment by sbc100** [comment]
Done
