### ISSUE TITLE
Can we tag wasi-sdk-8?

### ISSUE THREAD

**Issue by sbc100** [CraneStation/wasi-sdk#71]
I'd like to get a release that includes the new tarball layout (f967f43) and the cmake file (350d45b)

**Comment by pchickey** [comment]
Go for it. You have the right privileges, right? If not lets get them for you...

**Comment by sbc100** [comment]
Whats the release process?  `git tag` ... then upload the binaries via the web interface?  We don't have automatic uploading of assets yet do we?

**Comment by sunfishcode** [comment]
If it's not too much trouble, would you mind looking at whether https://github.com/CraneStation/wasi-sdk/pull/72 and https://github.com/CraneStation/wasi-sdk/pull/73 can be pulled in? Thanks!

**Comment by pchickey** [comment]
@sbc100 github releases require an "annotated tag" which for some reason is a different tag (fooled me at first), so `git tag -a wasi-sdk-8`. Then, for the github release page, I usually just hack together a change log out of the git commit names.

We really should setup automatic uploading of assets but I never got around to it. I usually just build the Linux binaries on my laptop and then ask Tyler to build the mac binary on his.

**Comment by sbc100** [comment]
sgtm, I'll go through that process now, and maybe document it.

**Comment by sbc100** [comment]
I'll wait for #72 which is about to land ..

**Comment by sbc100** [comment]
OK I made the version 8 release.  Would you mind kicking the tires?

**Comment by sbc100** [comment]
@tyler would you mind uploading the mac version?  (I do have access to mac so I could do this too if its a lot of trouble for you).

**Comment by linux-china** [comment]
wasi-sdk-8.0-macos.tar.gz absent?

**Comment by pchickey** [comment]
We don't have artifacts uploading from CI working, so we're waiting for a team member to do the build and upload from a macbook. We'll try to get it finished today

**Comment by saghul** [comment]
Gentle reminder.

**Comment by sbc100** [comment]
I'm happy to try and create and upload the mac archive, but I've not done it before.  @tyler how to do you do it?  Presumably you can't use the docker script on mac?

**Comment by pchickey** [comment]
Tyler uploaded it a few hours ago.

To build it you use the same `make package` target as we run inside the docker container.

I'll put some time into getting GH Actions to upload the built artifact for tags. @alexcrichton just did some work for that on Wasmtime and Cranelift that I can crib from.

**Comment by sbc100** [comment]
Currently I think one needs to `make package` as root right?  It would be nice if we could fix this at some point.
