### ISSUE TITLE
<algorithm> is not supported

### ISSUE THREAD

**Issue by txus** [CraneStation/wasi-sdk#99]
If we have an `example.cpp` like:

```cpp
#import <algorithm>

int main() {
	printf("hello world");
	return 0;
}
```

Using regular compilation works:

```bash
clang -Os -s -o a.out example.cpp
```

Where as targeting wasm and pointing to the right sysroot doesn't:

```bash
clang --target=wasm32-unknown-wasi --sysroot /tmp/wasi-libc -Os -s -o a.wasm example.cpp
```

Output:

```
hey.cpp:1:9: fatal error: 'algorithm' file not found
#import <algorithm>
        ^~~~~~~~~~~
1 error generated.
```

Is there something I'm missing? I'm relatively new to cross-compilation so it might be an oversight on my part. Thank you!

**Comment by sunfishcode** [comment]
Are you using the wasi-sdk sysroot?

**Comment by txus** [comment]
@sunfishcode yes!

**Comment by sbc100** [comment]
I looks like are you passing wasi-libc as the `--sysroot`.  wasi-libc is just the source code for the C library.   You probably want wasi-sdk instead which includes a compiled and installed version of wasi-libc (among other things): https://github.com/CraneStation/wasi-sdk/releases.

**Comment by txus** [comment]
@sbc100 I tried pointing sysroot at `~/Code/wasi-sdk` (downloaded from the link you sent me, but still the same error. Are you able to reproduce it on your machine?

**Comment by sbc100** [comment]
The sysroot path is under `share/wasi-sysroot` withing the SDK.

**Comment by txus** [comment]
Thank you, it worked!
